services:



  backend:
    build:
      context: ./backend
    ports:
      - "127.0.0.1:5030:5030"
    volumes:
      - ./backend/src:/app/src
    networks:
      - app-network

  ollama:
    build:
      context: ./ollama
    ports:
      - "127.0.0.1:11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - ollama
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/htpasswd/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
